services:
  strapi:
    build: ./memorial-strapi
    ports:
      - "1339:1337"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_CLIENT=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=hFwI/@MvZJJ[Y2WBq£1,(BN8\[-8Yu5^
      - DATABASE_HOST=database
      - EMAIL_SENDER_ADDRESS=noreply@elephahealth.com
      - APP_KEYS="toBeModified1,toBeModified2"
      - API_TOKEN_SALT=tobemodified
      - ADMIN_JWT_SECRET=tobemodified
      - TRANSFER_TOKEN_SALT=tobemodified
      - JWT_SECRET=RWjsAzs32r8nqfpqP1dLlA==
      - BOT_TOKEN=6652038217:AAEY0Znq7UHaM4aP7WF8ZXnP6Ef99sFd-B4
      - CHAT_IDS=-276800548,
    command: /bin/sh -c "yarn run start"
    depends_on:
      - database-platform
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      nw:
        aliases:
          - strapi
  database-platform:
    image: postgres:15.1-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hFwI/@MvZJJ[Y2WBq£1,(BN8\[-8Yu5^
    volumes:
      - elof_database-platform:/var/lib/postgresql/data2
    networks:
      nw:
        aliases:
          - database
  front:
    restart: always
    ports:
      - "9149:80"
    build:
      context: ./memorial-front
      dockerfile: Dockerfile
    env_file:
      - ./memorial-front/.env
volumes:
  elof_database-platform:

networks:
  nw:
  share:
    driver:
      bridge
