services:
  strapi:
    build: ./memorial-strapi
    ports:
      - "1339:1337"
    env_file:
      - ./memorial-strapi/.env
    command: /bin/sh -c "yarn run start"
    depends_on:
      - database-platform
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      nw:
        aliases:
          - strapi
  database-platform:
    image: postgres:15.1-alpine
    restart: always
    expose:
      - "5432"
    env_file:
      - ./memorial-strapi/.env
    volumes:
      - elof_database-memorial:/var/lib/postgresql/data2
    networks:
      nw:
        aliases:
          - database
  front:
    restart: always
    ports:
      - "9149:80"
    build:
      context: ./memorial-front
      dockerfile: Dockerfile
    env_file:
      - ./memorial-front/.env

volumes:
  elof_database-memorial:

networks:
  nw:
  share:
    driver:
      bridge
